### PR TITLE
prov/gni: swat malloc - no proto type warning

### PR DESCRIPTION
**Pull request by hppritcha**
If one configures libfabric with
export CFLAGS="-g"
and compiles with the gcc 5.1.0 compiler,
one gets a bunch of warning about no prototype
for malloc.

This commit suppresses these warnings.

@e-harvey 
@sungeunchoi 

Signed-off-by: Howard Pritchard howardp@lanl.gov

### CODE REVIEW

**Comment by sungeunchoi** [comment]
I'm using 5.1.0 and -g and -Wall, and I don't see this warning.  I thought some of us saw this earlier this week and it just required reconfiguring.  Don't know why it helped (maybe some env vars changed).

**Comment by hppritcha** [comment]
I did do ./autogen.sh and configure again but still see the warnings.

**Comment by hppritcha** [comment]
```
/include/fi.h: In function 'mem_dup':
./include/fi.h:78:14: warning: implicit declaration of function 'malloc' [-Wimplicit-function-declaration]
  if ((dest = malloc(size)))
              ^
./include/fi.h:78:14: warning: incompatible implicit declaration of built-in function 'malloc'
./include/fi.h:78:14: note: include '<stdlib.h>' or provide a declaration of 'malloc'
  CCLD     prov/gni/test/gnitest
make[1]: Leaving directory `/cray/css/u17/n17276/libfabric-cray'
n17276@tiger:/cray/css/users/n17276/libfabric-cray> (topic/new_vc_setup2 *)which gcc
/opt/gcc/5.1.0/bin/gcc
```

**Comment by e-harvey** [comment]
Has stdlib.h been included in fi.h?  It's looks like it needs to be included.

**Comment by hppritcha** [comment]
@e-harvey that is probably a better solution.
I'll try a PR into upstream instead of merging this one.
